export const authUsers = [
  {
    id: 'usr_001',
    name: 'Arjun Mehta',
    email: 'individual@demo.com',
    phone: '+91 98765 43210',
    avatar: '',
    role: 'individual',
    plan: 'basic',
    joinedDate: '2025-08-15',
    devicesCount: 4,
    familyMembers: 0,
    twoFactorEnabled: true,
    lastLogin: new Date().toISOString(),
    password: 'demo123',
  },
  {
    id: 'usr_002',
    name: 'Priya Sharma',
    email: 'family@demo.com',
    phone: '+91 87654 32109',
    avatar: '',
    role: 'family',
    plan: 'family',
    joinedDate: '2025-06-20',
    devicesCount: 6,
    familyMembers: 3,
    twoFactorEnabled: true,
    lastLogin: new Date().toISOString(),
    password: 'demo123',
  },
] as const;
